name: GLuaFixer

on:
  pull_request:
    paths:
      - 'lua/**'

jobs:
  Lint:
    uses: FPtje/GLuaFixer/.github/workflows/glualint.yml@master
    with:
      config: "https://cfc.gg/configs/gluafixer/glualint.json"
